### ISSUE TITLE
Shifting origin script makes all game objects covered by map on shift

### ISSUE THREAD

**Issue by darvin** [melowntech/vts-browser-unity-plugin#10]
I setup camera and map to have shifting origin. When shift happens, map seems to overlap everything in camera. video attached

https://youtu.be/MWEhpWL7e9M

**Comment by darvin** [comment]
oh, for some reason shifting origin sets Y of camera to 0 when X is changed more than threshold. any idea why?

**Comment by malytomas** [comment]
The threshold is measured as _3D_ euclidean distance. When the shift happens, the focused object is moved to _0,0,0_ (it is moved in all three coordinates, and also rotated).
Do you have Vts _Object_ Shifting Origin on all the objects that should shift alongside the map?
Furthermore, I am not sure if it works well when changing position in the editor.

**Comment by darvin** [comment]
@malytomas what is the purpose of whole shifting origin thing?.. It sounds like grossly misunderstood it

**Comment by malytomas** [comment]
There are two points to it:
- floating point precision - as you walk away from the start, the precision is worse and worse. The camera starts to shake, objects are flickering and so on. Physics simulations are impacted even more.
- the Earth is round, so as you walk further away, eg. direction of the gravity changes.

The shifting origin mitigates both problems.

**Comment by darvin** [comment]
@malytomas Thanks! my problem was fixed by creating "root" object for all game objects in the scene except for map, adding them to it as a children, and assigning shifting origin to that object instead of camera.

Perhaps couple static game objects in the sample scene would be helpful for clarification of usage

**Comment by malytomas** [comment]
As I think about it, this may have solved the problem for now, but might actually add more issues later.

Assuming that you are going to move far enough that you actually need to use shifting origin, you should not aggregate the objects like this, because that may break the floating point precision again.

The correct approach is to actually have an _object shifting origin_ component on all the objects (except the map). This allows to keep the floating point precision under control for each object independently.

I hope that makes sense?

It is obvious now that I should add more objects to the sample scene. Thanks for pointing that out.

**Comment by malytomas** [comment]
Actually, aggregating the objects like that will break due to the changing rotation. So adding the _object shifting origin_ to each object is the only correct way.

Just to be clear, the _object shifting origin_ behaves similar to _rigid body_. If you have a character that is composed of several parts, you add the _object shifting origin_ to the root object of the character.
