### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by 5y** [melowntech/vts-browser-unity-plugin#5]
Hello,

It would be great if anyone could let me know how to use the data in the offline mode.

Thanks.
Reza

**Comment by malytomas** [comment]
Hi Reza,
take a look at our https://melown.readthedocs.io/en/latest/ documentation. There are instructions to install VTS server that can serve the vts plugin in unity over localhost connection.

However, this kind of defeats the purpose of the vts plugin, which is specifically designed to stream data over network. If you have data available offline, you may prefer to use them in unity (directly or with another terrain plugin).
Hope this helps.

Cheers,
Tomáš Malý

**Comment by 5y** [comment]
Thank you @malytomas for your response.
can I use VTS plugin Offline or Online mode on the android phone?
I think we have no limitation on the server side. But I'm not sure VTS works on the android phone as a mobile application.

Thanks.

**Comment by malytomas** [comment]
Unfortunately, vts browser currently does not work on android. I see you have already put a thumb up on the respective issue.

**Comment by martdob** [comment]
> Thank you @malytomas for your response.
> can I use VTS plugin Offline or Online mode on the android phone?
> I think we have no limitation on the server side. But I'm not sure VTS works on the android phone as a mobile application.
> Thanks.

The lack of Android support is the biggest disadvantage of the VTS plugin which would be otherwise the perfect solution for our project. In the theory, it should be possible to concert the source code to a native Android code. However, the workload seems to be pretty high.

**Comment by LX-0910** [comment]
请问，可以使用缓存的方式，来实现离线版的vts吗

**Comment by LX-0910** [comment]
Can we use caching to implement the offline version of VTS？

**Comment by LX-0910** [comment]
hello,
Can we use caching to implement the offline version of VTS？
liuxiang.

**Comment by malytomas** [comment]
Hi liuxiang,

vts browser caches downloaded data (can be disabled), but some resources are always downloaded anew (cannot be disabled). These include authentication token, mapconfig, bound and free layer snippets etc.

You could use nginx or similar proxy caches. Also configure the vts browser to disable caching, so that data are not unnecessarily duplicated on disk.

However, I have to say again that this defeats the purpose of VTS, which is designed for streaming data. For offline landscapes, you may have better luck with some alternative solution in Unity.

**Comment by LX-0910** [comment]
Thank you for your response.
We're going to do an offline version of earth.Is there a way to put data into unity?
